builds:
    -   id: pak-extracter
        main: ./cmd/pak-extracter/main.go
        binary: pak-extracter
        flags:
            - -trimpath
        ldflags:
            - -s -w -X main.build={{.Version}}
        targets:
            - windows_amd64
            - linux_amd64
        env:
            - CGO_ENABLED=1
            - >-
              {{- if eq .Os "windows" }}
                {{- if eq .Arch "amd64" }}CC=x86_64-w64-mingw32-gcc{{- end }}
              {{- end }}
        hooks:
            pre:
                - apt install -y gcc-mingw-w64
    -   id: datasheet-converter
        main: ./cmd/datasheet-converter/main.go
        binary: datasheet-converter
        flags:
            - -trimpath
        ldflags:
            - -s -w -X main.build={{.Version}}
        targets:
            - windows_amd64
            - linux_amd64
    -   id: object-stream-converter
        main: ./cmd/object-stream-converter/main.go
        binary: object-stream-converter
        flags:
            - -trimpath
        ldflags:
            - -s -w -X main.build={{.Version}}
        targets:
            - windows_amd64
            - linux_amd64
    -   id: asset-catalog-parser
        main: ./cmd/asset-catalog-parser/main.go
        binary: asset-catalog-parser
        flags:
            - -trimpath
        ldflags:
            - -s -w -X main.build={{.Version}}
        targets:
            - windows_amd64
            - linux_amd64
archives:
    -   format: zip
        name_template: "{{ .ProjectName  }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
